### ISSUE TITLE
Sources for creating a similar project

### ISSUE THREAD

**Issue by SahilSharma1701** [GaganRajSingh/Talk-2-PDF#1]
Hi Gagan,

I recently came across your project while exploring similar work in openAI. Could you share the resources you used to build your project? I'm particularly interested in learning more about LangChain and vector databases.

If you followed any specific tutorials, could you please provide the links?

Thanks!

**Comment by GaganRajSingh** [comment]
Hey Sahil!

I found [this](https://www.youtube.com/watch?v=au2WVVGUvc8) video to be a good starting point. I tried implementing the same thing along with a couple of tweaks related to my own requirements.

**Comment by SahilSharma1701** [comment]
Thanks! And any specific video for creating the chat app? Loved the way you made it so responsive using react

**Comment by GaganRajSingh** [comment]
For chat UI, I did not refer to any video.
